name: CI/CD - pipeline

on:
  push:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # m√•ske include build og test senere

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: jose9894
          password: ${{secrets.DOCKER_ACCESS_TOKEN}}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./restaurant
          push: true
          tags: jose9894/frontend:latest